dist: trusty
language: cpp

compiler:
 - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
  
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "RayTracer"
  skip_cleanup: true
  on:
    tags: true

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make